### ISSUE TITLE
Is this Software *and Data* Carpentry?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-retreat-2015#10]
Please check with @tracykteal about making it explicitly that this is for Software _and Data_ Carpentry instructors.

**Comment by tracykteal** [comment]
Yes, definitely for both! Are there details for this somewhere?

**Comment by jiffyclub** [comment]
@BillMills has started a web page at http://swcarpentry.github.io/instructor-retreat-2015/ and there's an upcoming blog post at https://github.com/swcarpentry/site/pull/1089.

**Comment by ttimbers** [comment]
Hi Tracy, We are working on a blog post and website right now and will be releasing it soon. Briefly, it will happen on Sat Nov 14

**Comment by gvwilson** [comment]
#9 will close #10.

**Comment by ttimbers** [comment]
@tracykteal I also sent a PR so that Data Carpentry will be included on the website.

**Comment by katieannemills** [comment]
Closing per @gvwilson's comment since #9 has been merged. Glad to have Data Carpentry on board!
