### ISSUE TITLE
Where site.github.url is defined?

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/instructor-retreat-2015#13]
Related with #12.

@BillMills could you help me find where `site.github.url` is defined?

```
$ grep -r github.url .
./_includes/head.html:  <link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.github.url }}">
./_includes/head.html:  <link rel="stylesheet" href="{{ "/css/bootstrap.css" | prepend: site.github.url }}">
./_includes/head.html:  <link rel="stylesheet" href="{{ "/css/custom.css" | prepend: site.github.url }}">
./_includes/header.html:          <img alt="Software Carpentry logo" src="{{site.github.url}}/img/software-carpentry-banner.png">
```

**Comment by katieannemills** [comment]
All gh-pages sites have some default metadata injected into them by GitHub on the `site.github` object, see spec [here](https://help.github.com/articles/repository-metadata-on-github-pages/#available-repository-metadata). Hope this helps!

**Comment by rgaiacs** [comment]
@BillMills Thanks for the information. I'm closing this in favor of #19.
