### ISSUE TITLE
Contributorship workshops?

### ISSUE THREAD

**Issue by ttimbers** [swcarpentry/instructor-retreat-2015#15]
We are planning to run Contributorship workshops globally via Google Hangouts to remind/reinforce how to contribute back to the lesson material. I think we need 2-3 of these (one in Australasia, North America/South America and Europe /Africa/Asia). 

Who knows this topic well and wants to do one of these globally? Or do you know someone who's arm we could twist to do this?

cc @gvwilson @tracykteal @jiffyclub @rgaiacs @BillMills

**Comment by rgaiacs** [comment]
> Who knows this topic well and wants to do one of these globally?

I will ping our lesson maintainers. And I can do it if needed.

**Comment by ChristinaLK** [comment]
I'd be happy to do a pull request demo.

**Comment by ttimbers** [comment]
Great @ChristinaLK I'll put you down for a global PR demo! I'll put you down for the North America / South America time zone.

**Comment by ttimbers** [comment]
@rgaiacs do we have any lesson maintainers in Austrailia and Europe / Africa / Asia time zones? If so, can you please ask them to do this?

**Comment by ttimbers** [comment]
@ChristinaLK I have you down for a PR contributorship session at 1:00 pm EST on the planning etherpad (https://etherpad.mozilla.org/swc-instructor-helper-retreat-2015) does that work?

**Comment by ttimbers** [comment]
@gvwilson do you want to do the European time zone contributorship session at 10:00 AM GMT?

**Comment by rgaiacs** [comment]
> @rgaiacs do we have any lesson maintainers in Austrailia and Europe / Africa / Asia time zones? If so, can you please ask them to do this?

I will send emails around.

**Comment by ChristinaLK** [comment]
Yes, 1 pm EST is great.

**Comment by gvwilson** [comment]
Sure, why not.

**Comment by ttimbers** [comment]
@gvwilson fantastic! Does 11:00 AM GMT work?

**Comment by gvwilson** [comment]
Sure, but is GMT the same as UK time at that point?  (Damn daylight 
savings...)

**Comment by ttimbers** [comment]
@gvwilson daylight savings time is frustrating! But I think 11 is better than 10 am since the U Manchester site wont be kicking off until 10am?

**Comment by gvwilson** [comment]
I'll be there when you need me.  Currently trying to find a site in 
London, since folks don't seem willing to come to Canterbury.

**Comment by jiffyclub** [comment]
Are these going to be run the same day as the retreat?

**Comment by gvwilson** [comment]
That's been my assumption - am I wrong?

**Comment by ttimbers** [comment]
@jiffyclub yes - we will have several of these global sessions in each time zone. Local sites can choose which ones they tune into. The remainder of their day will be local teaching practice sessions.

**Comment by rgaiacs** [comment]
@ttimbers Do you need more instructors for this?

**Comment by ttimbers** [comment]
One more for Austrailia time as Greg said he would do the Europe time.

Thanks!
Tiff

On Thu, Sep 24, 2015 at 3:41 PM, Raniere Silva notifications@github.com
wrote:

> @ttimbers https://github.com/ttimbers Do you need more instructors for
> this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/instructor-retreat-2015/issues/15#issuecomment-143068440
> .

## 

Tiffany A. Timbers, PhD
Banting Postdoctoral fellow, Leroux Lab
Department of Molecular Biology and Biochemistry
Simon Fraser University
8888 University Drive
Burnaby, BC, V5A 1S6

604-803-4962

tiffany.timbers@gmail.com
tiffanytimbers.com
@TiffanyTimbers

**Comment by rgaiacs** [comment]
@DamienIrving, @IsaKiko, @dbarneche and @orchid00 Could you run the Contributorship workshops for Australia?

**Comment by orchid00** [comment]
Hi @rgaiacs Is there a date set? and what needs to be covered? I did a few contributions to the material but I'm not sure if I could answer many questions :P. Definitely Damien has more expertise

**Comment by IsaKiko** [comment]
@rgaiacs Possibly! Is there any material we should cover?

**Comment by rgaiacs** [comment]
> Is there a date set?

November 14th.

> and what needs to be covered?

How to fork, clone, change and send a pull request to one of our lessons.

> I did a few contributions to the material

@orchid00 That's all we need. =)

> Is there any material we should cover?

@IsaKiko There is no write material since we just looking for show the workflow to contribute to one lesson.

**Comment by ttimbers** [comment]
@orchid00 @IsaKiko are either of you up for it? Or do you want to co-teach it? Would love to get this on the schedule soon :)

**Comment by IsaKiko** [comment]
@ttimbers sign me up.

**Comment by ttimbers** [comment]
Thank-you @IsaKiko !! I have you down for 3 AM GMT to do a globally broadcast contributorship session. Thanks again :)

**Comment by ttimbers** [comment]
@IsaKiko I am trying to connect with everyone who is giving a global broadcast via email to make sure you have all the technical stuff down pat for their sessions at the retreat. I cannot find your email address, can you please email me? tiffany.timbers@gmail.com 
Thanks!

**Comment by gvwilson** [comment]
@ttimbers good to close?

**Comment by ttimbers** [comment]
@gvwilson yes
