### ISSUE TITLE
Website text

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#2]
As always, there's a balance to be struck between needing clear details but not too many words - text edits welcome! [Website here](http://swcarpentry.github.io/instructor-retreat-2015/).

**Comment by ttimbers** [comment]
Website looks great @BillMills! Small suggestions are that we add Data Carpentry and that we add another line in Hosting a Site to let hosts know they need to create a local schedule/plan. PR sent to add these things https://github.com/swcarpentry/instructor-retreat-2015/pull/11

**Comment by rgaiacs** [comment]
Website looks :sparkles: !!! Thanks @BillMills.

**Comment by katieannemills** [comment]
thanks, both!
