### ISSUE TITLE
Ideas for retreat sessions and topics

### ISSUE THREAD

**Issue by k8hertweck** [swcarpentry/instructor-retreat-2015#20]
Share ideas for potential sessions that you would like to see at the instructor retreat. These might be short, quick demos, or more extensive tutorials; topics may include general teaching tips/tricks or more specific examples.

**Comment by k8hertweck** [comment]
Using [Socrative](http://www.socrative.com) to administer multiple choice questions to students. You can also use this system to retain records of student performance on questions.

**Comment by k8hertweck** [comment]
A quick demo of setting up the shell for a workshop (trimming text in prompt, sending shell output to Dropbox file that students can access).

**Comment by ttimbers** [comment]
@k8hertweck could you give a global session on one of these? Would love to have this in the line-up for tomorrow's launch!

**Comment by ttimbers** [comment]
@k8hertweck I have you down for a socrative session at 4:00 PM EST on the planning etherpad (https://etherpad.mozilla.org/swc-instructor-helper-retreat-2015) please feel free to choose a different topic or time.

**Comment by k8hertweck** [comment]
Sounds good to me!

**Comment by ttimbers** [comment]
@remi-daigle could you do your Github session sans command line at 1:00 PM GMT / 10 am ADT? That's what I've tentatively put you down for. Or if there's a better time, please choose it and update https://etherpad.mozilla.org/swc-instructor-helper-retreat-2015

**Comment by remi-daigle** [comment]
@ttimbers if it's OK, I moved to 4PM GMT given that I'm the only instructor in town (although there are a couple more 1-3 hrs drive away) and with the change back to standard time (Nov 1?) 1PM GMT is 9AM AST (how's that for a time-zone mind melt!). I just don't think I can get many people to show up on a Saturday morning.

**Comment by ttimbers** [comment]
@remi-daigle sounds good to me! And thanks for the heads up about the time change - I think I need to check over all my times...

**Comment by apawlik** [comment]
@remi-daigle @ttimbers We (Europe sites) would welcome sessions between 10am and 4pm GMT! :-)

**Comment by ChristinaLK** [comment]
It would be cool to have someone talk through installing software (particularly SWC-used pieces), covering multiple OS's. Maybe a tag-team effort for a few people?

**Comment by ttimbers** [comment]
+1 @ChristinaLK , do you know anyone who'd like to do that? We can also put a call out for a volunteer to do such a session on the discuss list and twitterverse.

**Comment by jiffyclub** [comment]
I could talk about installing stuff, maybe not on Windows. (Though note that I'm not 100% sure I'll be able to attend at all.)

**Comment by ChristinaLK** [comment]
I don't have any good suggestions, so discuss/twitter is probably the best place to find volunteers...

**Comment by andreww** [comment]
I would love to see a session on python 3 for those of us who have yet to make the leap. Or maybe we can collaboratively create and test a short self-study guide for instructors? (Not that I think the leap is very difficult, but I think a firm shove would be useful.)

**Comment by katieannemills** [comment]
@andreww - I think that's a great idea; let's hash out the details in #28.

**Comment by ttimbers** [comment]
@jiffyclub having you talk about installing stuff would be great, and we can see if we can find a windows expert to partner up with you to cover that OS, as long as you have Mac and Linux covered. Thanks for volunteering!

**Comment by jiffyclub** [comment]
@ttimbers for scheduling purposes I'm on the west coast.

**Comment by jdcorless** [comment]
Hi @ttimbers, I have been working on a split-screen approach to teaching git at the command line to help students visualize the concepts.  I could give a presentation on that.

**Comment by ttimbers** [comment]
@jdcorless that would be cool! Where are you located (so I know what time zone your in for scheduling).

**Comment by jdcorless** [comment]
Dallas, TX

**Comment by ttimbers** [comment]
@jiffyclub I have you down for 11:00 PM GMT / 3:00 PM PST for a session on software installation. @jdcorless I have you down for 6:00 PM GMT / 4:00 PM CST for a session on version control.

**Comment by jiffyclub** [comment]
Okay. @ChristinaLK, if you have specific things you'd like addressed please let me know.

**Comment by ChristinaLK** [comment]
I was mostly thinking of "common errors + how to fix them", maybe some generalized strategies for dealing with installation issues.  Off the top of my head: "command not found" messages and how to add things to the PATH, how git installs on mac (do you need xcode? this has always been a mystery to me), what the swc windows installer does.

**Comment by ttimbers** [comment]
@jiffyclub will you be doing your session remotely or from one of the West coast sites (and if so, which one?)?

**Comment by jiffyclub** [comment]
I'll most likely be at the Davis site. I don't think there's one in the Bay
Area yet?

**Comment by jesford** [comment]
I would like to see another session on Interactive Learning (currently led by Lex Nederbragt), run at a time that works for PST people... maybe 7 or 10pm GMT. Are there any materials for this? The etherpad link for notes on the session seems to be broken.

**Comment by ttimbers** [comment]
@jesford - If session leaders OK with this, the early sessions will be available on youtube after their broadcast time and thus Seattle (and others) could watch @lexnederbragt 's session at a later time although he wouldn't be there to answer questions. Alternatively, someone could do a session on this topic again during the retreat at a later time point.

**Comment by jesford** [comment]
@ttimbers - sweet, I didn't realize that was an option!

**Comment by ttimbers** [comment]
@jdcorless I am trying to connect with all people giving a global broadcast via email so I can make sure everyone is technically prepared for the Retreat. Can you please email me: tiffany.timbers@gmail.com
Thanks!

**Comment by ttimbers** [comment]
@jiffyclub  we still need  your Google Hangout on Air link for the broadcast on Saturday. Instructions on how to create it are [here](https://github.com/swcarpentry/instructor-retreat-2015/blob/gh-pages/How_to_setup_global_broadcast.md). Please let @BillMills or I know if you need help setting it up and/or if you'd like to try out a test session (they are slightly different than the regular Google Hangouts).

**Comment by jiffyclub** [comment]
All set: https://plus.google.com/events/ctpt0he4m0b7subavhr1samurro

**Comment by ttimbers** [comment]
awesome, thanks @jiffyclub

**Comment by ttimbers** [comment]
@pbanaszkiewicz @leszektarkowski we still need your Google Hangout on Air link for the broadcast on Saturday. Instructions on how to create it are [here](https://github.com/swcarpentry/instructor-retreat-2015/blob/gh-pages/How_to_setup_global_broadcast.md). Please let @BillMills or I know if you need help setting it up and/or if you'd like to try out a test session (they are slightly different than the regular Google Hangouts).
