### ISSUE TITLE
AV & communication for broadcast sessions

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#31]
Alright - time to start thinking about AV strategy! I just added links to (currently non-existant) etherpads for each live session to the schedule; this is probably the most familiar way to collect notes and let people ask questions remotely. Will add in actual etherpads shortly.

For video, we should be able to set up a google hangout on air for speakers, and distribute the read-(watch?)-only link to the simulcast youtube video for the audience. Any alternate suggestions or requests? I'm happy with anything, but now's the time to start pulling those details together.

**Comment by ttimbers** [comment]
@BillMills I agree, let's do Google Hangouts on Air for the speakers, and we can have the topics column in the schedule table link to each Google Hangouts on Air session. As long as the speakers are good with this, then these links will link to the youtube video of their session afterwards so they can be watched later in other time zones, or even after the retreat. We will of course leave this decision up to each speaker. 

I'm going to work on a very clear and simple set of instructions on how to set up a Google Hangout on Air, and then send the instructions out to each speaker by Friday Oct. 16th. I will ask them to each test out setting this up, and send me the link to their test session. I can then check each link to make sure it worked and follow-up with any that seemed to have technical issues. I will also offer to meet to walk anyone through this that is might be having troubles.
