### ISSUE TITLE
"cool things" compendium

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-retreat-2015#32]
I'm not sure if this should be a broadcast session, but it would be cool to curate lists of miscellaneous resources as part of the retreat, stuff like: 

a) references/tutorials commonly recommended by SWC instructors as follow-up material
b) "fun" stuff like comics, quotes, gifs
c) "required reading" - favorite blogs or twitter feeds on computing, and especially computing education

I'm not sure how this would happen, but just wanted to throw it out there as a possible idea.

**Comment by katieannemills** [comment]
I like it - keep in mind, the broadcast sessions don't all have to be solo-lecture-demo style; roundtables, discussions and other collaborative conversations are all fair game, and may lend themselves well to something like this.
