### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-retreat-2015#37]
I'm volunteering to do a walk through of the SQL lesson, if that would be of interest to people.  Early morning in Central Standard time would be best...

**Comment by katieannemills** [comment]
Cool, thanks! Maybe something like 1PM UTC? cc @ttimbers

**Comment by ttimbers** [comment]
Two global broadcast sessions, you rock @ChristinaLK ! 1pm UTC is open on the schedule if you want it!

**Comment by ChristinaLK** [comment]
I can make that work.

**Comment by ChristinaLK** [comment]
Could I be switched to 7PM UTC or 10PM UTC (10PM would be preferable...)
