### ISSUE TITLE
functionality

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#4]
Are all the links working? How do things look in your browser of choice? [Website here](http://swcarpentry.github.io/instructor-retreat-2015/).

**Comment by ttimbers** [comment]
- Blog post and Google Hangout link bring you back to the retreat main page - but I imagine that's intentional until we merge it?
- Everything else works on Chrome for me.

**Comment by rgaiacs** [comment]
> Blog post and Google Hangout link bring you back to the retreat main page - but I imagine that's intentional until we merge it?

Yes. We need to publish the blog post first. We can get the Google Hangout early.

@gvwilson Could you create/schedule a Google Hangout on Air using https://www.youtube.com/channel/UCp_EGqMlGrLu-ElIbCwYfrQ ?

**Comment by ttimbers** [comment]
@rgaiacs @gvwilson Do we have a Google Hangout on Air set up yet?

**Comment by ttimbers** [comment]
@gvwilson can we please merge the blog post (https://github.com/swcarpentry/site/pull/1089) for tomorrow's launch at 10:00 AM EST?

**Comment by gvwilson** [comment]
Certainly - the site is being built automatically every hour, so I'll 
merge around 14:00 UK time so that it's up for 15:00 UK time (10:00 
Eastern).  I'll fill in the 'Category' field then if no one else does it 
first (I suggest "Instructor Retreat").

**Comment by rgaiacs** [comment]
> Do we have a Google Hangout on Air set up yet?

@gvwilson Could you do that and provide us with the link?

**Comment by gvwilson** [comment]
I've only ever set up a regular Google Hangout, not an On Air - has 
someone else done it?

**Comment by rgaiacs** [comment]
> I've only ever set up a regular Google Hangout, not an On Air - has someone else done it?

o/ Start at https://plus.google.com/hangouts/onair, click on "Create a Hangouts On Air" and fill the form.

**Comment by ttimbers** [comment]
@gvwilson I think we are still waiting for the blog post (https://github.com/swcarpentry/site/pull/1089) to be merged

**Comment by gvwilson** [comment]
Doing it now...

**Comment by raynamharris** [comment]
The Austin pin on the map has a non-functional link to the building rather than to our etherpad https://etherpad.mozilla.org/swc-instructor-retreat-2015-austin

**Comment by katieannemills** [comment]
Austin now linked - thanks @raynamharris!

**Comment by gvwilson** [comment]
@BillMills good to close?
