### ISSUE TITLE
chatroom

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#5]
I suggest Gitter as a minimum-barrier-to-entry chat room to support worldwide communication in the website text; how does everyone feel about this? I tried to set it up, but I don't think I have quite the right permissions. [Website here](http://swcarpentry.github.io/instructor-retreat-2015/).

**Comment by katieannemills** [comment]
@rgaiacs pointed out in https://github.com/swcarpentry/site/pull/1089 we have a slack somewhere, so sure - let's go with that. Please someone post or PR links / credentials we can add to the site to direct people there, and we can close this out.

**Comment by jiffyclub** [comment]
See https://github.com/swcarpentry/site/pull/1089#issuecomment-140438646 for the links.
