### ISSUE TITLE
etherpad text

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#6]
If you click on the Vancouver pin, there's a link to a [template site etherpad](https://etherpad.mozilla.org/swc-instructor-retreat-2015-vancouver) - how does this look? Need to agree this template before we start spawning tons of copies.

**Comment by ttimbers** [comment]
Added twitter handles for Software and Data Carpentry, as well as "local/locally" in a few spot in Schedule & Activity Suggestions to make it more clear that most people will be practice teaching locally (not as scary as globally!)

**Comment by katieannemills** [comment]
cool, thanks - also added in an explicit callout to the code of conduct. If there are no further comments, I think this is good to go (ping @DamienIrving - feel free to just cut and paste this text to make the etherpad for Melbourne I was asking after).
