### ISSUE TITLE
event scheduling

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#7]
It occurred to me while pulling this together that there might be collisions between the global broadcast sessions, and local-only teaching practice (or whatever) sessions. Suggestions on how to navigate? Would be nice to have two rooms at each site, but this might be getting overly ambitious.

**Comment by ttimbers** [comment]
I think we might have to leave this up to hosts/community members of local sites to worry about choosing what they tune into globally. Ideally, I think hosts need to make a schedule ahead of the event with who's teaching what locally, and when, taking into account which global sessions they want to watch. Sites with less people might watch more global events, whereas sites with more, might not.

Or is this too wild west and we need to provide more structure? Or at the very least, make it clear to hosts that they have to build a schedule for their site, picking and choosing global and local sessions?

**Comment by katieannemills** [comment]
I'm a big fan of non-prescriptive prescriptions - let's just let them self organize, and as you said, emphasize the need to shepherd people through a rough schedule.
