### ISSUE TITLE
actual sites

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/instructor-retreat-2015#8]
I put some dummy pins on the map just to show what it's going to look like, but do we have a few actual sites we can seed with?

**Comment by rgaiacs** [comment]
@katyhuff @DamienIrving @apawlik @ethanwhite @ctb Could you let us know if you have plans to be part in the retreat and if we could put some pins where you are based?

**Comment by DamienIrving** [comment]
The University of Melbourne (Research Platform Services in particular) will definitely be a host site. The pin on the map could go here:
https://www.google.com.au/maps/place/Doug+McDonell+Building/@-37.799009,144.962886,15z/data=!4m2!3m1!1s0x0:0x4ea4ce999ce3b96d

which is:
Level 3, 
Doug McDonell Building, 
University of Melbourne

I'll chat to the team tomorrow about what we'd like to do/acheive at the retreat.

**Comment by ttimbers** [comment]
@tracykteal will Data Carpentry want to host a site as well?

**Comment by ttimbers** [comment]
@BillMills @rgaiacs After merging https://github.com/swcarpentry/instructor-retreat-2015/pull/14 the map and dummy pins disappeared - not sure what broke.

**Comment by rgaiacs** [comment]
![screen shot 2015-09-17 at 01 11 15](https://cloud.githubusercontent.com/assets/1506457/9924778/071704e8-5cd9-11e5-9757-e8cc4ca81e6d.png)

@ttimbers the map is still visible to me (both on Firefox and Chrome).

**Comment by ttimbers** [comment]
@rgaiacs OK, now I see them.

**Comment by tracykteal** [comment]
@ttimbers working on locations

**Comment by ctb** [comment]
On Wed, Sep 16, 2015 at 08:46:09PM -0700, Raniere Silva wrote:

> @katyhuff @DamienIrving @apawlik @ethanwhite @ctb Could you let us know if you have plans to be part in the retreat and if we could put some pins where you are based?

@tracykteal may be doing something; if I'm not doing childcare, I'll
participate at the same location as DC.

**Comment by apawlik** [comment]
I'm figuring things out in the UK. Most likely Manchester or Edinburgh.

**Comment by katyhuff** [comment]
If one of the other BIDS fellows (@karthik, @jkitzes, @fatmai, @dturek) wanted to lead the local setup, this might be a good use for the BIDS space in Berkeley (I can secure the space, but probably can't lead that day)... 

@tracykteal @ctb : do you wanna use this as an excuse to visit Berkeley, combining Davis and Berkeley at BIDS? There are little rooms at BIDS where kids could play while we're retreating... we could call them BIDS kids.

**Comment by ttimbers** [comment]
@DamienIrving I've added you and U. Melbourne as a host in the planning etherpad. Can you please check/add all details? Please see line 46 at https://etherpad.mozilla.org/swc-instructor-helper-retreat-2015

**Comment by katieannemills** [comment]
@DamienIrving you're pinned on the map; let me know when you have an etherpad pulled together, so we can link you from there, too.

@tracykteal @ctb @katyhuff @apawlik let me know when you do - one(+) in California and one in the UK along with Melbourne is enough coverage to launch.

**Comment by raynamharris** [comment]
I could host one... not sure if there are many people in the Austin, TX or nearby.

9-5 pm Central 
GDC 7.514 
https://www.google.com/maps/place/Bill+and+Melinda+Gates+Computer+Science+Complex,+Austin,+TX+78712/@30.286253,-97.736434,17z/data=!3m1!4b1!4m2!3m1!1s0x8644b59c98544379:0x1a0c2b90248ca2ed

**Comment by katieannemills** [comment]
thanks, @raynamharris - you're on the map! Let me know when you have a chance to pull together an etherpad (see the [example from Vancouver](https://etherpad.mozilla.org/swc-instructor-retreat-2015-vancouver)), and I'll add the link.

As for number of people, don't forget about helpers, and people on the instructor training wait list; also nothing wrong with inviting curious folks to come out and ask questions about maybe getting involved with SWC, too.

**Comment by DamienIrving** [comment]
@BillMills Here's the Etherpad for Melbourne: 
https://etherpad.mozilla.org/swc-instructor-retreat-2015-melbourne

**Comment by katieannemills** [comment]
Thanks @DamienIrving - everyone else, I'd like to announce broadly on the Tuesday social media cycle; we can still add sites and site details afterwards, but it'd be good to have as much on the table as possible for that push. Open an issue with details here, or email the mentorship committee at mentoring@lists.software-carpentry.org

**Comment by raynamharris** [comment]
Here is the link to the Austin, TX site

https://etherpad.mozilla.org/swc-instructor-retreat-2015-austin

**Comment by apawlik** [comment]
I'm confirming that @softwaresaved will run a site at the University of Manchester, Kilburn Building 10am-4pm local time. I added the details to the Etherpad.

**Comment by ttimbers** [comment]
Thank-you @apawlik !

**Comment by ttimbers** [comment]
Thank-you @raynamharris

**Comment by katieannemills** [comment]
@apawlik, thanks for organizing a site! You're on the map, but do you have your own etherpad I can link from your map pin? Sorry if I missed the link somewhere...

**Comment by apawlik** [comment]
@BillMills https://swcuk.etherpad.mozilla.org/retreat-manchester

**Comment by tracykteal** [comment]
This is the link to the Davis location

https://etherpad.mozilla.org/swc-instructor-retreat-2015-davis

We'll have a family friendly version at our house.

**Comment by ttimbers** [comment]
Awesome @tracykteal ! Thank-you for organizing and making it family friendly!

**Comment by ttimbers** [comment]
@tracykteal I've added it to the general planning etherpad - please edit as you see fit: https://etherpad.mozilla.org/swc-instructor-helper-retreat-2015
